# Generated by Django 5.1.5 on 2026-03-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.mosque', verbose_name='Mosquee')),
            ],
            options={
                'verbose_name': 'Adherent',
                'verbose_name_plural': 'Adherents',
                'db_table': 'membership_member',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Ex: 2026', verbose_name='Annee')),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant attendu par adherent')),
                ('is_active', models.BooleanField(default=False, verbose_name='Annee active')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_years', to='core.mosque', verbose_name='Mosquee')),
            ],
            options={
                'verbose_name': 'Annee de cotisation',
                'verbose_name_plural': 'Annees de cotisation',
                'db_table': 'membership_year',
                'ordering': ['-year'],
                'unique_together': {('mosque', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('autre', 'Autre')], default='cash', max_length=20, verbose_name='Mode')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.member', verbose_name='Adherent')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to='core.mosque', verbose_name='Mosquee')),
                ('membership_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.membershipyear', verbose_name='Annee de cotisation')),
            ],
            options={
                'verbose_name': 'Paiement cotisation',
                'verbose_name_plural': 'Paiements cotisations',
                'db_table': 'membership_payment',
                'ordering': ['-date'],
            },
        ),
    ]
