# Generated by Django 5.1.5 on 2026-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membershippayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment_frequency',
            field=models.CharField(choices=[('once', 'En une fois'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('biannual', 'Semestriel'), ('annual', 'Annuel')], default='annual', help_text='Fréquence attendue pour détecter les retards automatiquement', max_length=20, verbose_name='Périodicité de paiement'),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('autre', 'Autre')], default='virement', max_length=20, verbose_name='Moyen de paiement préféré'),
        ),
    ]
