# Generated by Django 5.1.5 on 2026-04-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact_name', models.CharField(max_length=200, verbose_name='Nom du contact principal')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone1', models.CharField(blank=True, default='', max_length=50, verbose_name='Telephone principal')),
                ('phone2', models.CharField(blank=True, default='', max_length=50, verbose_name='Telephone secondaire')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='core.mosque', verbose_name='Mosquee')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'db_table': 'school_family',
                'ordering': ['primary_contact_name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prenom')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('level', models.CharField(help_text='Ex: NP, N1, N2...', max_length=50, verbose_name='Niveau')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.mosque', verbose_name='Mosquee')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='school.family', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'db_table': 'school_child',
                'ordering': ['family__primary_contact_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: "2025-2026"', max_length=50, verbose_name='Label')),
                ('start_date', models.DateField(verbose_name='Date de debut')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Annee active')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='core.mosque', verbose_name='Mosquee')),
            ],
            options={
                'verbose_name': 'Annee scolaire',
                'verbose_name_plural': 'Annees scolaires',
                'db_table': 'school_year',
                'ordering': ['-start_date'],
                'unique_together': {('mosque', 'label')},
            },
        ),
        migrations.CreateModel(
            name='SchoolPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('autre', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='school.child', verbose_name='Enfant (optionnel)')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.family', verbose_name='Famille')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_payments', to='core.mosque', verbose_name='Mosquee')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.schoolyear', verbose_name='Annee scolaire')),
            ],
            options={
                'verbose_name': 'Paiement ecole',
                'verbose_name_plural': 'Paiements ecole',
                'db_table': 'school_payment',
                'ordering': ['-date'],
            },
        ),
    ]
