# Generated by Django 5.1.5 on 2026-03-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='level',
            field=models.CharField(help_text='Ex: NP, N1, N2...', max_length=50, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='family',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telephone principal'),
        ),
        migrations.AlterField(
            model_name='family',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telephone secondaire'),
        ),
    ]
