# Generated by Django 5.1.5 on 2026-04-14 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_v2_billing_fields'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: "N1 - Debutants"', max_length=100, verbose_name='Nom de la classe')),
                ('level_code', models.CharField(help_text='Ex: "NP", "N1", "N2", "CORAN"', max_length=20, verbose_name='Code niveau')),
                ('room', models.CharField(blank=True, default='', max_length=100, verbose_name='Salle')),
                ('schedule_notes', models.TextField(blank=True, default='', verbose_name='Horaires / notes')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacite max')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='core.mosque', verbose_name='Mosquee')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.schoolyear', verbose_name='Annee scolaire')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='Professeur principal')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'school_class',
                'ordering': ['order', 'name'],
                'unique_together': {('mosque', 'school_year', 'level_code')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la seance')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes prof')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.mosque')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school.class', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Seance',
                'verbose_name_plural': 'Seances',
                'db_table': 'school_attendance_session',
                'ordering': ['-date'],
                'unique_together': {('school_class', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GradePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: "Trimestre 1"', max_length=100, verbose_name='Nom')),
                ('start_date', models.DateField(verbose_name='Debut')),
                ('end_date', models.DateField(verbose_name='Fin')),
                ('is_published', models.BooleanField(default=False, verbose_name='Bulletins publies')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_periods', to='core.mosque')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_periods', to='school.schoolyear', verbose_name='Annee scolaire')),
            ],
            options={
                'verbose_name': 'Periode',
                'verbose_name_plural': 'Periodes',
                'db_table': 'school_grade_period',
                'ordering': ['order'],
                'unique_together': {('school_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'En retard'), ('excused', 'Absent excuse')], default='present', max_length=10, verbose_name='Statut')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.child', verbose_name='Enfant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.attendancesession', verbose_name='Seance')),
            ],
            options={
                'verbose_name': 'Presence',
                'verbose_name_plural': 'Presences',
                'db_table': 'school_attendance',
                'ordering': ['child__first_name'],
                'unique_together': {('session', 'child')},
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Inscription active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.child', verbose_name='Enfant')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.mosque', verbose_name='Mosquee')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.class', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'school_enrollment',
                'ordering': ['child__first_name'],
                'unique_together': {('school_class', 'child')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(choices=[('TB', 'Tres bien'), ('B', 'Bien'), ('AB', 'Assez bien'), ('P', 'Peut mieux faire'), ('I', 'Insuffisant')], max_length=2, verbose_name='Mention')),
                ('appreciation', models.TextField(blank=True, default='', verbose_name='Appreciation libre')),
                ('absences_count', models.PositiveSmallIntegerField(default=0, verbose_name='Nb absences sur la periode')),
                ('surah_memorized_count', models.PositiveSmallIntegerField(default=0, verbose_name='Nb sourates memorisees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.child', verbose_name='Enfant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_created', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='school.class', verbose_name='Classe')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.gradeperiod', verbose_name='Periode')),
            ],
            options={
                'verbose_name': 'Appreciation',
                'verbose_name_plural': 'Appreciations',
                'db_table': 'school_grade',
                'ordering': ['period__order', 'child__first_name'],
                'unique_together': {('child', 'period')},
            },
        ),
        migrations.CreateModel(
            name='QuranProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveSmallIntegerField(choices=[(1, 'Al-Fatiha'), (2, 'Al-Baqara'), (3, 'Al-Imran'), (4, 'An-Nisa'), (5, 'Al-Maida'), (6, 'Al-Anam'), (7, 'Al-Araf'), (8, 'Al-Anfal'), (9, 'At-Tawba'), (10, 'Yunus'), (11, 'Hud'), (12, 'Yusuf'), (13, 'Ar-Rad'), (14, 'Ibrahim'), (15, 'Al-Hijr'), (16, 'An-Nahl'), (17, 'Al-Isra'), (18, 'Al-Kahf'), (19, 'Maryam'), (20, 'Ta-Ha'), (21, 'Al-Anbiya'), (22, 'Al-Hajj'), (23, 'Al-Muminun'), (24, 'An-Nur'), (25, 'Al-Furqan'), (26, 'Ash-Shuara'), (27, 'An-Naml'), (28, 'Al-Qasas'), (29, 'Al-Ankabut'), (30, 'Ar-Rum'), (31, 'Luqman'), (32, 'As-Sajda'), (33, 'Al-Ahzab'), (34, 'Saba'), (35, 'Fatir'), (36, 'Ya-Sin'), (37, 'As-Saffat'), (38, 'Sad'), (39, 'Az-Zumar'), (40, 'Ghafir'), (41, 'Fussilat'), (42, 'Ash-Shura'), (43, 'Az-Zukhruf'), (44, 'Ad-Dukhan'), (45, 'Al-Jathiya'), (46, 'Al-Ahqaf'), (47, 'Muhammad'), (48, 'Al-Fath'), (49, 'Al-Hujurat'), (50, 'Qaf'), (51, 'Adh-Dhariyat'), (52, 'At-Tur'), (53, 'An-Najm'), (54, 'Al-Qamar'), (55, 'Ar-Rahman'), (56, 'Al-Waqia'), (57, 'Al-Hadid'), (58, 'Al-Mujadila'), (59, 'Al-Hashr'), (60, 'Al-Mumtahana'), (61, 'As-Saf'), (62, 'Al-Jumuah'), (63, 'Al-Munafiqun'), (64, 'At-Taghabun'), (65, 'At-Talaq'), (66, 'At-Tahrim'), (67, 'Al-Mulk'), (68, 'Al-Qalam'), (69, 'Al-Haqqa'), (70, 'Al-Maarij'), (71, 'Nuh'), (72, 'Al-Jinn'), (73, 'Al-Muzzammil'), (74, 'Al-Muddaththir'), (75, 'Al-Qiyama'), (76, 'Al-Insan'), (77, 'Al-Mursalat'), (78, 'An-Naba'), (79, 'An-Naziat'), (80, 'Abasa'), (81, 'At-Takwir'), (82, 'Al-Infitar'), (83, 'Al-Mutaffifin'), (84, 'Al-Inshiqaq'), (85, 'Al-Buruj'), (86, 'At-Tariq'), (87, 'Al-Ala'), (88, 'Al-Ghashiya'), (89, 'Al-Fajr'), (90, 'Al-Balad'), (91, 'Ash-Shams'), (92, 'Al-Layl'), (93, 'Ad-Duha'), (94, 'Ash-Sharh'), (95, 'At-Tin'), (96, 'Al-Alaq'), (97, 'Al-Qadr'), (98, 'Al-Bayyina'), (99, 'Az-Zalzala'), (100, 'Al-Adiyat'), (101, 'Al-Qaria'), (102, 'At-Takathur'), (103, 'Al-Asr'), (104, 'Al-Humaza'), (105, 'Al-Fil'), (106, 'Quraysh'), (107, 'Al-Maun'), (108, 'Al-Kawthar'), (109, 'Al-Kafirun'), (110, 'An-Nasr'), (111, 'Al-Masad'), (112, 'Al-Ikhlas'), (113, 'Al-Falaq'), (114, 'An-Nas')], verbose_name='Sourate')),
                ('status', models.CharField(choices=[('not_started', 'Non commence'), ('in_progress', 'En cours'), ('memorized', 'Memorise'), ('review', 'En revision')], default='not_started', max_length=15, verbose_name='Statut')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Debut')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Memorisee le')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notes prof')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_progress', to='school.child', verbose_name='Enfant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quran_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Coran',
                'verbose_name_plural': 'Progressions Coran',
                'db_table': 'school_quran_progress',
                'ordering': ['child', 'surah_number'],
                'unique_together': {('child', 'surah_number')},
            },
        ),
    ]
