# Generated by Django 5.1.5 on 2026-04-17 17:19

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('school', '0003_schoolpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpayment',
            name='status',
            field=models.CharField(choices=[('validated', 'Valide'), ('pending', 'En attente')], default='validated', help_text='validated = en caisse / pending = a valider par le tresorier', max_length=15, verbose_name='Statut'),
        ),
    ]
