# Generated by Django 5.1.5 on 2026-04-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('membership', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la cagnotte')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('icon', models.CharField(default='🎯', max_length=10, verbose_name='Icône (emoji)')),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Objectif (€)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Clôturée')], default='active', max_length=10, verbose_name='Statut')),
                ('show_on_kpi', models.BooleanField(default=True, verbose_name='Afficher sur la page KPI publique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.mosque')),
            ],
            options={
                'verbose_name': 'Cagnotte',
                'verbose_name_plural': 'Cagnottes',
                'db_table': 'treasury_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du pointage')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note / Commentaire')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Saisi par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Pointage de caisse',
                'verbose_name_plural': 'Pointages de caisse',
                'db_table': 'treasury_cashcount',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, choices=[('don', 'Don / Sadaqa'), ('loyer', 'Loyer'), ('salaire', 'Salaire / Honoraires'), ('facture', 'Facture / Charges'), ('ecole', 'Ecole coranique'), ('cotisation', 'Cotisation adherent'), ('projet', 'Projet / Travaux'), ('subvention', 'Subvention'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('IN', 'Entree'), ('OUT', 'Sortie')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('autre', 'Autre')], default='cash', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('regime_fiscal', models.CharField(blank=True, choices=[('', 'Non précisé'), ('1901', 'Loi 1901 — Association'), ('1905', 'Loi 1905 — Culte')], default='', max_length=4, verbose_name='Régime fiscal')),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('import', 'Import CSV')], default='manual', max_length=10, verbose_name='Source')),
                ('import_operation_id', models.CharField(blank=True, db_index=True, help_text='Identifiant unique de la ligne dans le CSV bancaire — sert à éviter les doublons', max_length=250, null=True, verbose_name='N° opération (import)')),
                ('import_status', models.CharField(blank=True, choices=[('validated', 'Validée'), ('pending', 'En attente de validation')], help_text='Null pour les transactions saisies manuellement', max_length=15, null=True, verbose_name='Statut import')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Null = espèces / non bancaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.bankaccount', verbose_name='Compte bancaire')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='treasury.campaign', verbose_name='Cagnotte liée')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='school.family', verbose_name='Famille (école)')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membership.member', verbose_name='Adhérent')),
                ('membership_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membership.membershipyear', verbose_name='Année de cotisation')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.mosque')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='school.schoolyear', verbose_name='Année scolaire')),
            ],
            options={
                'db_table': 'treasury_transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Coupure (€)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('cash_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='treasury.cashcount', verbose_name='Pointage')),
            ],
            options={
                'verbose_name': 'Ligne de coupure',
                'verbose_name_plural': 'Lignes de coupures',
                'db_table': 'treasury_cashdenomination',
                'ordering': ['-denomination'],
                'unique_together': {('cash_count', 'denomination')},
            },
        ),
    ]
