# Generated by Django 5.1.5 on 2026-03-14 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('don', 'Don / Sadaqa'), ('loyer', 'Loyer'), ('salaire', 'Salaire / Honoraires'), ('facture', 'Facture / Charges'), ('ecole', 'Ecole coranique'), ('cotisation', 'Cotisation adherent'), ('projet', 'Projet / Travaux'), ('subvention', 'Subvention'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('IN', 'Entree'), ('OUT', 'Sortie')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('autre', 'Autre')], default='cash', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.mosque')),
            ],
            options={
                'db_table': 'treasury_transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
