# Generated by Django 5.1.5 on 2026-05-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_v1_features'),
        ('treasury', '0002_payment_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurytransaction',
            name='staff',
            field=models.ForeignKey(blank=True, help_text="Rempli automatiquement si le libellé correspond au name_keyword d'un membre du personnel", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.staff', verbose_name='Personnel lié'),
        ),
    ]
