# Generated by Django 5.1.5 on 2026-03-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_phone_max_length_50'),
        ('school', '0002_phone_level_max_length_50'),
        ('treasury', '0003_transaction_regime_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurytransaction',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='school.family', verbose_name='Famille (école)'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membership.member', verbose_name='Adhérent'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='membership_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membership.membershipyear', verbose_name='Année de cotisation'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='school.schoolyear', verbose_name='Année scolaire'),
        ),
    ]
