# Generated by Django 5.1.5 on 2026-04-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_bankaccount_dispatchrule'),
        ('treasury', '0005_add_bankaccount_import_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du pointage')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note / Commentaire')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Saisi par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Pointage de caisse',
                'verbose_name_plural': 'Pointages de caisse',
                'db_table': 'treasury_cashcount',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Coupure (€)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('cash_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='treasury.cashcount', verbose_name='Pointage')),
            ],
            options={
                'verbose_name': 'Ligne de coupure',
                'verbose_name_plural': 'Lignes de coupures',
                'db_table': 'treasury_cashdenomination',
                'ordering': ['-denomination'],
                'unique_together': {('cash_count', 'denomination')},
            },
        ),
    ]
