# Generated by Django 5.1.5 on 2026-04-13 12:09

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant URL')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50, verbose_name='Fuseau horaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mosquée',
                'verbose_name_plural': 'Mosquées',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('TRESORIER', 'Trésorier'), ('ECOLE_MANAGER', 'École Manager'), ('VIEWER', 'Lecture seule')], default='', max_length=20, verbose_name='Rôle')),
                ('permissions_data', models.JSONField(default=core.models._default_permissions, help_text='JSON : {school:{read,write,delete}, membership:…, treasury:…, campaigns:…, users:…, settings:…}', verbose_name='Permissions granulaires')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'core_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Texte à rechercher (insensible à la casse)', max_length=200, verbose_name='Mot-clé')),
                ('field', models.CharField(choices=[('label', 'Libellé'), ('detail', 'Détail'), ('both', 'Libellé ou Détail')], default='both', max_length=10, verbose_name='Champ à inspecter')),
                ('category', models.CharField(choices=[('don', 'Don / Sadaqa'), ('loyer', 'Loyer'), ('salaire', 'Salaire / Honoraires'), ('facture', 'Facture / Charges'), ('ecole', 'Ecole coranique'), ('cotisation', 'Cotisation adhérent'), ('projet', 'Projet / Travaux'), ('subvention', 'Subvention'), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie à affecter')),
                ('direction', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('auto', 'Automatique (selon Débit/Crédit)')], default='auto', help_text="'auto' utilise Débit/Crédit du CSV pour déterminer IN ou OUT", max_length=5, verbose_name='Direction')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text="Plus petit = évalué en premier. En cas d'égalité, ordre alphabétique.", verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_rules', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Règle de dispatch',
                'verbose_name_plural': 'Règles de dispatch',
                'db_table': 'core_dispatchrule',
                'ordering': ['priority', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex : "Compte 1901 — Banque Populaire"', max_length=100, verbose_name='Libellé')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom de la banque')),
                ('account_number', models.CharField(help_text="Numéro tel qu'il apparaît dans les exports CSV de la banque", max_length=50, verbose_name='Numéro de compte')),
                ('regime', models.CharField(choices=[('1901', 'Loi 1901 — Association'), ('1905', 'Loi 1905 — Culte'), ('autre', 'Autre')], default='1901', max_length=10, verbose_name='Régime fiscal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'db_table': 'core_bankaccount',
                'ordering': ['regime', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('entity', models.CharField(max_length=50, verbose_name='Entité')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID entité')),
                ('payload', models.JSONField(default=dict, verbose_name='Données')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'db_table': 'core_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MosqueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_levels', models.JSONField(default=list, help_text='Ex : ["NP","N1","N2","N3","N4","N5","N6"]', verbose_name='Niveaux école')),
                ('school_fee_default', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif école par défaut')),
                ('school_fee_mode', models.CharField(choices=[('annual', 'Annuel'), ('monthly', 'Mensuel')], default='annual', max_length=20, verbose_name='Mode tarif école')),
                ('membership_fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant cotisation')),
                ('membership_fee_mode', models.CharField(choices=[('per_person', 'Par personne'), ('per_family', 'Par famille')], default='per_person', max_length=20, verbose_name='Mode cotisation')),
                ('active_school_year_label', models.CharField(help_text='Ex : "2025-2026"', max_length=50, verbose_name='Année scolaire active')),
                ('receipt_logo_url', models.URLField(blank=True, default='', help_text='URL publique vers le logo de la mosquée (PNG/JPG recommandé)', verbose_name='URL du logo (reçus PDF)')),
                ('receipt_address', models.TextField(blank=True, default='', help_text='Adresse complète de la mosquée affichée sur les reçus', verbose_name='Adresse (reçus PDF)')),
                ('receipt_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone (reçus PDF)')),
                ('receipt_legal_mention', models.TextField(blank=True, default='', help_text='Ex : "Association loi 1901 — Reçu de don déductible à 66% dans la limite de 20% du revenu imposable"', verbose_name='Mention légale (reçus PDF)')),
                ('show_kpi_school', models.BooleanField(default=True, verbose_name='KPI : afficher École')),
                ('show_kpi_membership', models.BooleanField(default=True, verbose_name='KPI : afficher Adhérents')),
                ('show_kpi_treasury', models.BooleanField(default=True, verbose_name='KPI : afficher Trésorerie')),
                ('show_kpi_campaigns', models.BooleanField(default=True, verbose_name='KPI : afficher Cagnottes')),
                ('kpi_refresh_secs', models.PositiveIntegerField(default=60, help_text='Valeurs conseillées : 30, 60, 120, 300', verbose_name='KPI : fréquence de rafraîchissement (secondes)')),
                ('smtp_host', models.CharField(blank=True, default='', help_text='Ex: smtp.gmail.com, ssl0.ovh.net', max_length=200, verbose_name='SMTP : hôte')),
                ('smtp_port', models.PositiveSmallIntegerField(default=587, help_text='587 (TLS/STARTTLS) ou 465 (SSL)', verbose_name='SMTP : port')),
                ('smtp_user', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP : utilisateur')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP : mot de passe')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='SMTP : utiliser TLS (STARTTLS)')),
                ('email_from', models.EmailField(blank=True, default='', help_text='Ex: noreply@mosquee-meximieux.fr', max_length=254, verbose_name='Expéditeur des emails')),
                ('email_subject_prefix', models.CharField(blank=True, default='[Mosquée Manager]', max_length=100, verbose_name='Préfixe sujet email')),
                ('mosque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Paramètres mosquée',
                'verbose_name_plural': 'Paramètres mosquées',
                'db_table': 'core_mosquesettings',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('role', models.CharField(choices=[('enseignant', 'Enseignant(e)'), ('imam', 'Imam / Prédicateur'), ('entretien', "Agent d'entretien"), ('comptable', 'Comptable / Trésorier'), ('gardien', 'Gardien / Accueil'), ('autre', 'Autre')], default='enseignant', max_length=20, verbose_name='Rôle')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Montant brut mensuel à titre indicatif', max_digits=8, null=True, verbose_name='Salaire mensuel (€)')),
                ('iban_fragment', models.CharField(blank=True, default='', help_text="Ex: 'ZABI' ou 'SAMAALI' — utilisé pour reconnaître les virements dans le CSV", max_length=50, verbose_name='Fragment IBAN / nom banque')),
                ('name_keyword', models.CharField(blank=True, default='', help_text="Texte recherché dans le libellé du virement (insensible à la casse). Ex: 'SABYA ZABI'", max_length=200, verbose_name='Mot-clé de reconnaissance')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Personnel',
                'db_table': 'core_staff',
                'ordering': ['role', 'full_name'],
            },
        ),
    ]
