# Generated by Django 6.0.2 on 2026-03-01 14:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant URL')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50, verbose_name='Fuseau horaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mosquée',
                'verbose_name_plural': 'Mosquées',
                'db_table': 'core_mosque',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('TRESORIER', 'Trésorier'), ('ECOLE_MANAGER', 'École Manager')], default='', max_length=20, verbose_name='Rôle')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'core_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('entity', models.CharField(max_length=50, verbose_name='Entité')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID entité')),
                ('payload', models.JSONField(default=dict, verbose_name='Données')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'db_table': 'core_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MosqueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_levels', models.JSONField(default=list, help_text='Ex : ["NP","N1","N2","N3","N4","N5","N6"]', verbose_name='Niveaux école')),
                ('school_fee_default', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif école par défaut')),
                ('school_fee_mode', models.CharField(choices=[('annual', 'Annuel'), ('monthly', 'Mensuel')], default='annual', max_length=20, verbose_name='Mode tarif école')),
                ('membership_fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant cotisation')),
                ('membership_fee_mode', models.CharField(choices=[('per_person', 'Par personne'), ('per_family', 'Par famille')], default='per_person', max_length=20, verbose_name='Mode cotisation')),
                ('active_school_year_label', models.CharField(help_text='Ex : "2025-2026"', max_length=50, verbose_name='Année scolaire active')),
                ('mosque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Paramètres mosquée',
                'verbose_name_plural': 'Paramètres mosquées',
                'db_table': 'core_mosquesettings',
            },
        ),
    ]
