# Generated by Django 5.1.5 on 2026-04-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Cloud Free'), ('starter', 'Starter — 19€/mois'), ('pro', 'Pro — 49€/mois'), ('premium', 'Premium — 89€/mois'), ('federation', 'Fédération — sur devis')], max_length=30, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_families', models.IntegerField(default=75, help_text='-1 = illimite')),
                ('max_users', models.IntegerField(default=1, help_text='-1 = illimite')),
                ('max_sms_month', models.IntegerField(default=0, help_text='-1 = illimite')),
                ('modules', models.JSONField(default=list, help_text='Ex: ["core", "school", "communication"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan tarifaire',
                'verbose_name_plural': 'Plans tarifaires',
                'db_table': 'core_plan',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', "Période d'essai"), ('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Résilié')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=10)),
                ('trial_end', models.DateField(blank=True, null=True, verbose_name='Fin essai')),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=200)),
                ('helloasso_subscription_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.mosque', verbose_name='Mosquée')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'core_subscription',
            },
        ),
    ]
