# Generated by Django 5.1.5 on 2026-04-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_plan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
