# Generated by Django 5.1.5 on 2026-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_plan_name_no_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price_monthly'], 'verbose_name': 'Plan tarifaire', 'verbose_name_plural': 'Plans tarifaires'},
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_name',
            field=models.CharField(default='', help_text='Nom affiche : Nidham Pro, Nidham Standard...', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible sur la page pricing'),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordre affichage'),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sms_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sms_used_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Plan actif pour nouvelles mosquees'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_families',
            field=models.IntegerField(default=30, help_text='-1 = illimite'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='modules',
            field=models.JSONField(default=list, help_text='Modules inclus. Tout changement via fixture, jamais dans le code.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='Identifiant technique : free_cloud, standard, pro, federation', max_length=50, unique=True),
        ),
    ]
