# Generated by Django 5.1.5 on 2026-03-16 12:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_permissions_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquesettings',
            name='email_from',
            field=models.EmailField(blank=True, default='', help_text='Ex: noreply@mosquee-meximieux.fr', max_length=254, verbose_name='Expéditeur des emails'),
        ),
        migrations.AddField(
            model_name='mosquesettings',
            name='email_subject_prefix',
            field=models.CharField(blank=True, default='[Mosquée Manager]', max_length=100, verbose_name='Préfixe sujet email'),
        ),
        migrations.AddField(
            model_name='mosquesettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='Ex: smtp.gmail.com, ssl0.ovh.net', max_length=200, verbose_name='SMTP : hôte'),
        ),
        migrations.AddField(
            model_name='mosquesettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP : mot de passe'),
        ),
        migrations.AddField(
            model_name='mosquesettings',
            name='smtp_port',
            field=models.PositiveSmallIntegerField(default=587, help_text='587 (TLS/STARTTLS) ou 465 (SSL)', verbose_name='SMTP : port'),
        ),
        migrations.AddField(
            model_name='mosquesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='SMTP : utiliser TLS (STARTTLS)'),
        ),
        migrations.AddField(
            model_name='mosquesettings',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP : utilisateur'),
        ),
        migrations.AlterField(
            model_name='mosquesettings',
            name='kpi_refresh_secs',
            field=models.PositiveIntegerField(default=60, help_text='Valeurs conseillées : 30, 60, 120, 300', verbose_name='KPI : fréquence de rafraîchissement (secondes)'),
        ),
        migrations.AlterField(
            model_name='mosquesettings',
            name='receipt_address',
            field=models.TextField(blank=True, default='', help_text='Adresse complète de la mosquée affichée sur les reçus', verbose_name='Adresse (reçus PDF)'),
        ),
        migrations.AlterField(
            model_name='mosquesettings',
            name='receipt_legal_mention',
            field=models.TextField(blank=True, default='', help_text='Ex : "Association loi 1901 — Reçu de don déductible à 66% dans la limite de 20% du revenu imposable"', verbose_name='Mention légale (reçus PDF)'),
        ),
        migrations.AlterField(
            model_name='mosquesettings',
            name='receipt_logo_url',
            field=models.URLField(blank=True, default='', help_text='URL publique vers le logo de la mosquée (PNG/JPG recommandé)', verbose_name='URL du logo (reçus PDF)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions_data',
            field=models.JSONField(default=core.models._default_permissions, help_text='JSON : {school:{read,write,delete}, membership:…, treasury:…, campaigns:…, users:…, settings:…}', verbose_name='Permissions granulaires'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('TRESORIER', 'Trésorier'), ('ECOLE_MANAGER', 'École Manager'), ('VIEWER', 'Lecture seule')], default='', max_length=20, verbose_name='Rôle'),
        ),
    ]
