# Generated by Django 5.1.5 on 2026-04-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_v2_billing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('TRESORIER', 'Trésorier'), ('ECOLE_MANAGER', 'École Manager'), ('TEACHER', 'Professeur'), ('SECRETARY', 'Secrétaire'), ('VIEWER', 'Lecture seule')], default='', max_length=20, verbose_name='Rôle'),
        ),
    ]
