# Generated by Django 5.1.5 on 2026-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_teacher_secretary_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquesettings',
            name='absence_alert_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text="Nombre d'absences consécutives avant envoi d'un email à la famille (défaut : 3)", verbose_name='Seuil alertes absences'),
        ),
    ]
