# Generated by Django 5.1.5 on 2026-04-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_smtp_settings_to_mosquesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex : "Compte 1901 — Banque Populaire"', max_length=100, verbose_name='Libellé')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom de la banque')),
                ('account_number', models.CharField(help_text="Numéro tel qu'il apparaît dans les exports CSV de la banque", max_length=50, verbose_name='Numéro de compte')),
                ('regime', models.CharField(choices=[('1901', 'Loi 1901 — Association'), ('1905', 'Loi 1905 — Culte'), ('autre', 'Autre')], default='1901', max_length=10, verbose_name='Régime fiscal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'db_table': 'core_bankaccount',
                'ordering': ['regime', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Texte à rechercher (insensible à la casse)', max_length=200, verbose_name='Mot-clé')),
                ('field', models.CharField(choices=[('label', 'Libellé'), ('detail', 'Détail'), ('both', 'Libellé ou Détail')], default='both', max_length=10, verbose_name='Champ à inspecter')),
                ('category', models.CharField(choices=[('don', 'Don / Sadaqa'), ('loyer', 'Loyer'), ('salaire', 'Salaire / Honoraires'), ('facture', 'Facture / Charges'), ('ecole', 'Ecole coranique'), ('cotisation', 'Cotisation adhérent'), ('projet', 'Projet / Travaux'), ('subvention', 'Subvention'), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie à affecter')),
                ('direction', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('auto', 'Automatique (selon Débit/Crédit)')], default='auto', help_text="'auto' utilise Débit/Crédit du CSV pour déterminer IN ou OUT", max_length=5, verbose_name='Direction')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text="Plus petit = évalué en premier. En cas d'égalité, ordre alphabétique.", verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_rules', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Règle de dispatch',
                'verbose_name_plural': 'Règles de dispatch',
                'db_table': 'core_dispatchrule',
                'ordering': ['priority', 'keyword'],
            },
        ),
    ]
