# Generated by Django 5.1.5 on 2026-05-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_absence_alert_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquesettings',
            name='membership_school_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Utilisé uniquement si règle = 'discount'", max_digits=8, verbose_name="Réduction cotisation si inscrit à l'école (€)"),
        ),
        migrations.AddField(
            model_name='mosquesettings',
            name='membership_school_rule',
            field=models.CharField(choices=[('separate', 'Séparé — cotisation toujours due'), ('included', "Incluse — cotisation offerte si inscrit à l'école"), ('discount', "Réduction — montant fixe déduit si inscrit à l'école")], default='separate', max_length=20, verbose_name='Règle cotisation / école'),
        ),
        migrations.AddField(
            model_name='mosquesettings',
            name='school_fee_tiers',
            field=models.JSONField(blank=True, default=dict, help_text='Ex: {"1": 300, "2": 400, "3": 450, "4+": 500}', verbose_name="Barème école par nombre d'enfants"),
        ),
        migrations.CreateModel(
            name='BankImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: "Banque Populaire — Compte 1901"', max_length=100, verbose_name='Nom du profil')),
                ('is_default', models.BooleanField(default=False, help_text="Si activé, ce profil est pré-sélectionné à l'import", verbose_name='Profil par défaut')),
                ('separator', models.CharField(default=';', help_text="Généralement ';' pour les banques françaises", max_length=5, verbose_name='Séparateur CSV')),
                ('encoding', models.CharField(default='utf-8-sig', help_text='utf-8-sig, latin-1, utf-8', max_length=20, verbose_name='Encodage')),
                ('date_format', models.CharField(default='%d/%m/%Y', help_text='Ex: %d/%m/%Y pour 23/04/2026', max_length=30, verbose_name='Format de date')),
                ('decimal_sep', models.CharField(choices=[(',', 'Virgule (France)'), ('.', 'Point (international)')], default=',', max_length=1, verbose_name='Séparateur décimal')),
                ('skip_rows', models.PositiveSmallIntegerField(default=0, help_text='0 = première ligne = en-têtes (cas standard)', verbose_name='Lignes à ignorer en début de fichier')),
                ('date_column', models.CharField(default='date', max_length=100, verbose_name='Colonne date')),
                ('label_column', models.CharField(default='libelle', max_length=100, verbose_name='Colonne libellé')),
                ('detail_column', models.CharField(blank=True, default='', help_text='Optionnel — utilisé pour enrichir le label', max_length=100, verbose_name='Colonne détail / informations complémentaires')),
                ('debit_column', models.CharField(blank=True, default='', help_text='Laisser vide si un seul champ montant avec signe', max_length=100, verbose_name='Colonne débit (sortie)')),
                ('credit_column', models.CharField(blank=True, default='', help_text='Laisser vide si un seul champ montant avec signe', max_length=100, verbose_name='Colonne crédit (entrée)')),
                ('amount_column', models.CharField(blank=True, default='', help_text='Utilisé si la banque met tout dans une seule colonne avec +/-', max_length=100, verbose_name='Colonne montant unique (avec signe)')),
                ('type_column', models.CharField(blank=True, default='', help_text="Optionnel — Ex: 'Type operation' pour catégorisation auto", max_length=100, verbose_name='Colonne type opération')),
                ('reference_column', models.CharField(blank=True, default='', help_text='Sert à détecter les doublons lors de ré-imports', max_length=100, verbose_name='Colonne référence / ID opération')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_import_profiles', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': "Profil d'import bancaire",
                'verbose_name_plural': "Profils d'import bancaire",
                'db_table': 'core_bankimportprofile',
                'ordering': ['-is_default', 'label'],
            },
        ),
    ]
