# Generated by Django 5.1.5 on 2026-04-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_bankaccount_dispatchrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('role', models.CharField(choices=[('enseignant', 'Enseignant(e)'), ('imam', 'Imam / Prédicateur'), ('entretien', "Agent d'entretien"), ('comptable', 'Comptable / Trésorier'), ('gardien', 'Gardien / Accueil'), ('autre', 'Autre')], default='enseignant', max_length=20, verbose_name='Rôle')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Montant brut mensuel à titre indicatif', max_digits=8, null=True, verbose_name='Salaire mensuel (€)')),
                ('iban_fragment', models.CharField(blank=True, default='', help_text="Ex: 'ZABI' ou 'SAMAALI' — utilisé pour reconnaître les virements dans le CSV", max_length=50, verbose_name='Fragment IBAN / nom banque')),
                ('name_keyword', models.CharField(blank=True, default='', help_text="Texte recherché dans le libellé du virement (insensible à la casse). Ex: 'SABYA ZABI'", max_length=200, verbose_name='Mot-clé de reconnaissance')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.mosque', verbose_name='Mosquée')),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Personnel',
                'db_table': 'core_staff',
                'ordering': ['role', 'full_name'],
            },
        ),
    ]
